{{- $global := .Values.global | default dict }}
{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    {{- if .Values.operator.extraLabels}}
    {{ toYaml .Values.operator.extraLabels | nindent 4 }}
    {{- end}}
  {{- with .Values.operator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  {{- if (.Values.operator.deployment | default dict).strategy }}
  strategy:
    {{- toYaml .Values.operator.deployment.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "operator.name" . }}
      app.kubernetes.io/instance: {{ .Chart.Name }}-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "operator.name" . }}
        app.kubernetes.io/instance: {{ .Chart.Name }}-operator
        {{- if .Values.operator.extraLabels}}
        {{ toYaml .Values.operator.extraLabels | nindent 8 }}
        {{- end}}
    spec:
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}
    {{- if .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.operator.nodeSelector | nindent 8 }}
    {{- end }}
    {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.operator.affinity }}
      affinity:
        {{- toYaml .Values.operator.affinity | nindent 8 }}
    {{- end }}
      containers:
      - name: operator
        command:
        - "/operator"
        env:
          - name: "RELEASE_NAMESPACE"
            value: {{ .Release.Namespace }}
          - name: "RELEASE_NAME"
            value: {{ .Chart.Name }}
        image: "
          {{- if and $global.registry (ne $global.registry "docker.io") }}{{ $global.registry }}
          {{- else }}{{ .Values.operator.image.registry }}
          {{- end }}/{{ .Values.operator.image.repository }}:
          {{- with .Values.operator.image.tag }}{{ . }}
          {{- else }}v{{ .Chart.Version }}{{ end }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8081
          name: http
        resources:
          {{- toYaml .Values.operator.resources | nindent 12 }}
{{- end }}
