apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-template
  namespace: {{ .Values.kcm.namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  secret.yaml: |
    {{` {{ copy "Secret" }} `}}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: {{ .Chart.Name }}-propagation
  namespace: {{ .Values.kcm.namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    localSourceRef:
      kind: ConfigMap
      name: {{ .Chart.Name }}-template
      namespace: {{ .Values.kcm.namespace }}
    deploymentType: Remote
    path: ""