{{- if .Values.rootCA.enabled }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ .Release.Name }}-ca-secret-propagation
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: member
  serviceSpec:
    services:
      - name: secret-deployment
        namespace: {{ $.Release.Namespace }}
        template: k0rdent-istio-base-propagation
    templateResourceRefs:
      - identifier: Secret
        resource:
          apiVersion: v1
          kind: Secret
          name: {{ $.Chart.Name }}-{{ `{{ .Cluster.metadata.namespace }}` }}-{{ `{{ .Cluster.metadata.name }}` }}-ca
          namespace: {{ $.Release.Namespace }}
{{- end }}