{{- if .Values.rootCA.enabled -}}
  {{- $common := include "istio.common.setup" . | fromJson -}}
  {{- $version := .Chart.Version | replace "." "-" -}}
  {{- $gatewayVersion := .Values.gateway.version | replace "." "-" -}}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ .Release.Name }}-network-with-gateway
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: member
      k0rdent.mirantis.com/istio-gateway: "true"
  serviceSpec:
    services:
      - name: k0rdent-istio
        namespace: {{ .Release.Namespace }}
        template: k0rdent-istio-{{ $version }}
        values: |
{{ include "istio.service.values" (dict "customRegistry" $common.customRegistry) | indent 10 }}
      - name: istio-gateway
        namespace: {{ .Release.Namespace }}
        template: k0rdent-istio-base-gateway-{{ $gatewayVersion }}
        values: |
          networkGateway: {{ `{{ .Cluster.metadata.name }}` }}-network
          labels:
            istio: eastwestgateway
        dependsOn:
          - name: k0rdent-istio
            namespace: {{ .Release.Namespace }}
      - name: gateway-template
        namespace: {{ .Release.Namespace }}
        template: k0rdent-istio-base-gateway-template
{{- end }}
