---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments/status
  verbs:
  - get
  - patch
  - update
